mysite/Prime/urls.py
from django.urls import path

from . import views

app_name = 'Prime'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('Prime.urls')),
    path('detail/', include('Prime.urls')),
]

mysite/Prime/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/Prime/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from .models import Question
from django.http import Http404

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    
    # template = loader.get_template('D:/Projects/Scrap-Data/Current Work Space/Django/mysite/Prime/templates/prime/index.html')
    # context = {
    #     'latest_question_list': latest_question_list,
    # }
    # return HttpResponse(template.render(context, request))

    context = {'latest_question_list': latest_question_list} # render, instead of loader
    return render(request, 'D:/Projects/Scrap-Data/Current Work Space/Django/mysite/Prime/templates/prime/index.html', context)

def detail(request, question_id):
    # return HttpResponse("You're looking at question %s." % question_id)

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, 'D:/Projects/Scrap-Data/Current Work Space/Django/mysite/Prime/templates/prime/detail.html', {'question': question})

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'D:/Projects/Scrap-Data/Current Work Space/Django/mysite/Prime/templates/prime/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/Prime/templates/prime/detail.html
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="utf-8" />
    <title>detail</title>
</head>

<body>
    <form action="{% url 'Prime:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>

</html>

mysite/Prime/templates/prime/index.html
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="utf-8" />
    <title>index</title>
</head>

<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="D:/Projects/Scrap-Data/Current Work Space/Django/mysite/Prime/templates/prime/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>

</html>

mysite/Prime/templates/prime/results.html
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="utf-8" />
    <title>index</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'Prime:detail' question.id %}">Vote again?</a>
</body>

</html>